general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # to turn on the screen after sleep.
}

listener {
    timeout = 900                                # 5 mins
    on-timeout = loginctl lock-session           # lock screen when timeout has passed
}

listener {
    timeout = 930                                # 5.5 mins
    on-timeout = hyprctl dispatch dpms off       # screen off after locking
    on-resume = hyprctl dispatch dpms on         # screen on when activity is detected
}
